# Generated by Django 3.1.4 on 2020-12-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True, 'ordering': ('-publish',)},
        ),
    ]
