# Generated by Django 3.1.4 on 2020-12-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0002_auto_20201221_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
    ]
