# Generated by Django 3.1.4 on 2020-12-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0006_post_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
